#!/bin/bash

# Docker Variables
containerid=$(docker ps -qf "name=vaultwarden")
imageid=$(docker images -q vaultwarden/server)
dockerversion=1.25.0

# Stop/RM Image
docker stop $containerid
docker rm $containerid
docker rmi $imageid

# Pull New Version
docker pull vaultwarden/server:$dockerversion

# Run New Version
docker run -d --name vaultwarden \
--restart=always \
-e ROCKET_TLS='{certs="/ssl/certs.perm",key="key.pem"}' \
-v /ssl/:/ssl/ \
-v /vw-data/:/data/ \
-p 443:80 \
vaultwarden/server:$dockerversion
